{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "896cc2b3-8b76-4897-8d4a-731e4dd7155a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "\n",
    "\n",
    "# --- Game Setup & State ---\n",
    "class TicTacToe:\n",
    "\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Tic-Tac-Toe\")\n",
    "        self.root.configure(bg=\"#0f172a\")  # Dark slate background\n",
    "        self.root.resizable(False, False)\n",
    "\n",
    "        # Game State Variables\n",
    "        self.current_player = \"X\"\n",
    "        self.board_state = [\"\"] * 9\n",
    "        self.game_active = True\n",
    "        self.scores = {\"X\": 0, \"O\": 0, \"Draws\": 0}\n",
    "\n",
    "        # Center the window on screen\n",
    "        self.center_window(420, 560)\n",
    "\n",
    "        # Build GUI Components\n",
    "        self.create_widgets()\n",
    "\n",
    "    def center_window(self, width, height):\n",
    "        \"\"\"Center the app window on screen.\"\"\"\n",
    "        self.root.update_idletasks()\n",
    "        screen_width = self.root.winfo_screenwidth()\n",
    "        screen_height = self.root.winfo_screenheight()\n",
    "        x = (screen_width // 2) - (width // 2)\n",
    "        y = (screen_height // 2) - (height // 2)\n",
    "        self.root.geometry(f\"{width}x{height}+{x}+{y}\")\n",
    "\n",
    "    def create_widgets(self):\n",
    "        \"\"\"Build and align all graphical components.\"\"\"\n",
    "        # 1. Main Title\n",
    "        self.title_label = tk.Label(\n",
    "            self.root,\n",
    "            text=\"TIC-TAC-TOE\",\n",
    "            font=(\"Helvetica\", 20, \"bold\"),\n",
    "            fg=\"#38bdf8\",\n",
    "            bg=\"#0f172a\",\n",
    "        )\n",
    "        self.title_label.pack(pady=(15, 5))\n",
    "\n",
    "        # 2. Scoreboard\n",
    "        self.score_frame = tk.Frame(\n",
    "            self.root, bg=\"#1e293b\", padx=15, pady=8, highlightthickness=0\n",
    "        )\n",
    "        self.score_frame.pack(pady=5)\n",
    "\n",
    "        self.score_label = tk.Label(\n",
    "            self.score_frame,\n",
    "            text=\"X: 0   |   Draws: 0   |   O: 0\",\n",
    "            font=(\"Helvetica\", 11, \"bold\"),\n",
    "            fg=\"#f8fafc\",\n",
    "            bg=\"#1e293b\",\n",
    "        )\n",
    "        self.score_label.pack()\n",
    "\n",
    "        # 3. Turn Status Indicator\n",
    "        self.status_label = tk.Label(\n",
    "            self.root,\n",
    "            text=\"Player X's Turn\",\n",
    "            font=(\"Helvetica\", 13, \"bold\"),\n",
    "            fg=\"#f43f5e\",\n",
    "            bg=\"#0f172a\",\n",
    "        )\n",
    "        self.status_label.pack(pady=10)\n",
    "\n",
    "        # 4. Grid Container (Board)\n",
    "        self.grid_frame = tk.Frame(\n",
    "            self.root, bg=\"#1e293b\", padx=10, pady=10, highlightthickness=0\n",
    "        )\n",
    "        self.grid_frame.pack()\n",
    "\n",
    "        # 5. Create 9 Clickable Cells\n",
    "        self.buttons = []\n",
    "        for i in range(9):\n",
    "            btn = tk.Button(\n",
    "                self.grid_frame,\n",
    "                text=\"\",\n",
    "                font=(\"Helvetica\", 24, \"bold\"),\n",
    "                width=4,\n",
    "                height=2,\n",
    "                bg=\"#334155\",\n",
    "                fg=\"#f8fafc\",\n",
    "                activebackground=\"#475569\",\n",
    "                activeforeground=\"#f8fafc\",\n",
    "                bd=0,\n",
    "                cursor=\"hand2\",\n",
    "                command=lambda idx=i: self.handle_click(idx),\n",
    "            )\n",
    "            row = i // 3\n",
    "            col = i % 3\n",
    "            btn.grid(row=row, column=col, padx=5, pady=5)\n",
    "            self.buttons.append(btn)\n",
    "\n",
    "        # 6. Restart Button\n",
    "        self.restart_btn = tk.Button(\n",
    "            self.root,\n",
    "            text=\"Restart Game\",\n",
    "            font=(\"Helvetica\", 11, \"bold\"),\n",
    "            bg=\"#38bdf8\",\n",
    "            fg=\"#0f172a\",\n",
    "            activebackground=\"#0284c7\",\n",
    "            activeforeground=\"#ffffff\",\n",
    "            bd=0,\n",
    "            padx=15,\n",
    "            pady=8,\n",
    "            cursor=\"hand2\",\n",
    "            command=self.reset_board,\n",
    "        )\n",
    "        self.restart_btn.pack(pady=18)\n",
    "\n",
    "    def handle_click(self, index):\n",
    "        \"\"\"Processes player moves on cell clicks.\"\"\"\n",
    "        # Prevent clicks on occupied tiles or finished games\n",
    "        if self.board_state[index] != \"\" or not self.game_active:\n",
    "            return\n",
    "\n",
    "        # Record Move\n",
    "        self.board_state[index] = self.current_player\n",
    "\n",
    "        # Style active tile according to symbol\n",
    "        color = \"#f43f5e\" if self.current_player == \"X\" else \"#38bdf8\"\n",
    "        self.buttons[index].config(text=self.current_player, fg=color)\n",
    "\n",
    "        # Check for Game Ending Conditions\n",
    "        self.check_game_over()\n",
    "\n",
    "    def check_game_over(self):\n",
    "        \"\"\"Checks for 3-in-a-row or draw states.\"\"\"\n",
    "        win_conditions = [\n",
    "            [0, 1, 2],\n",
    "            [3, 4, 5],\n",
    "            [6, 7, 8],  # Rows\n",
    "            [0, 3, 6],\n",
    "            [1, 4, 7],\n",
    "            [2, 5, 8],  # Columns\n",
    "            [0, 4, 8],\n",
    "            [2, 4, 6],  # Diagonals\n",
    "        ]\n",
    "\n",
    "        # Check Wins\n",
    "        for a, b, c in win_conditions:\n",
    "            if (\n",
    "                self.board_state[a]\n",
    "                == self.board_state[b]\n",
    "                == self.board_state[c]\n",
    "                == self.current_player\n",
    "            ):\n",
    "                self.game_active = False\n",
    "\n",
    "                # Highlight winning cells in green\n",
    "                for idx in (a, b, c):\n",
    "                    self.buttons[idx].config(bg=\"#22c55e\", fg=\"#ffffff\")\n",
    "\n",
    "                self.status_label.config(\n",
    "                    text=f\"Player {self.current_player} Wins!\", fg=\"#22c55e\"\n",
    "                )\n",
    "                self.scores[self.current_player] += 1\n",
    "                self.update_score()\n",
    "\n",
    "                messagebox.showinfo(\n",
    "                    \"Game Over\", f\"Player {self.current_player} wins the match!\"\n",
    "                )\n",
    "                return\n",
    "\n",
    "        # Check Draw\n",
    "        if \"\" not in self.board_state:\n",
    "            self.game_active = False\n",
    "            self.status_label.config(text=\"It's a Draw!\", fg=\"#eab308\")\n",
    "            self.scores[\"Draws\"] += 1\n",
    "            self.update_score()\n",
    "\n",
    "            messagebox.showinfo(\"Game Over\", \"It's a Draw!\")\n",
    "            return\n",
    "\n",
    "        # Switch Player\n",
    "        self.current_player = \"O\" if self.current_player == \"X\" else \"X\"\n",
    "        next_color = \"#f43f5e\" if self.current_player == \"X\" else \"#38bdf8\"\n",
    "        self.status_label.config(\n",
    "            text=f\"Player {self.current_player}'s Turn\", fg=next_color\n",
    "        )\n",
    "\n",
    "    def update_score(self):\n",
    "        \"\"\"Updates the text on the scoreboard.\"\"\"\n",
    "        self.score_label.config(\n",
    "            text=f\"X: {self.scores['X']}   |   Draws: {self.scores['Draws']}   |   O: {self.scores['O']}\"\n",
    "        )\n",
    "\n",
    "    def reset_board(self):\n",
    "        \"\"\"Resets tiles and state for a fresh match.\"\"\"\n",
    "        self.board_state = [\"\"] * 9\n",
    "        self.game_active = True\n",
    "        self.current_player = \"X\"\n",
    "\n",
    "        self.status_label.config(text=\"Player X's Turn\", fg=\"#f43f5e\")\n",
    "\n",
    "        for btn in self.buttons:\n",
    "            btn.config(text=\"\", bg=\"#334155\")\n",
    "\n",
    "\n",
    "# --- Main Application Execution ---\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = TicTacToe(root)\n",
    "    root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1fbdab1a-48c0-4723-822b-e83c2f0385ab",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
